const $ = (id) => document.getElementById(id);
const els = {
  sidebar: $('sidebar'), brandBtn: $('brandBtn'), toggleSidebarBtn: $('toggleSidebarBtn'), sidebarCloseIcon: $('sidebarCloseIcon'), sidebarOpenIcon: $('sidebarOpenIcon'), sidebarScroll: $('sidebarScroll'), sidebarProjectsSection: $('sidebarProjectsSection'), sidebarProjectsList: $('sidebarProjectsList'), newProjectBtn: $('newProjectBtn'), sidebarPagesList: $('sidebarPagesList'), refreshSidebarBtn: $('refreshSidebarBtn'), sidebarLoadMoreWrap: $('sidebarLoadMoreWrap'), sidebarLoadMoreBtn: $('sidebarLoadMoreBtn'), searchPagesBtn: $('searchPagesBtn'), sidebarSettingsBtn: $('sidebarSettingsBtn'),
  pageHeader: $('pageHeader'), welcomeView: $('welcomeView'), welcomeNewPageBtn: $('welcomeNewPageBtn'), welcomeSearchInput: $('welcomeSearchInput'), welcomeSearchResults: $('welcomeSearchResults'),
  saveBtn: $('saveBtn'), updateAppBtn: $('updateAppBtn'), refreshBtn: $('refreshBtn'), openViewMenuBtn: $('openViewMenuBtn'), newPageBtn: $('newPageBtn'), historyBtn: $('historyBtn'), deleteBtn: $('deleteBtn'), moreBtn: $('moreBtn'), moreMenu: $('moreMenu'),
  quickBothBtn: $('quickBothBtn'), quickEditorBtn: $('quickEditorBtn'), quickPreviewBtn: $('quickPreviewBtn'),
  titleInput: $('titleInput'), descriptionInput: $('descriptionInput'), dirtyBadge: $('dirtyBadge'), externalSyncNotice: $('externalSyncNotice'), externalSyncNoticeTitle: $('externalSyncNoticeTitle'), externalSyncNoticeMessage: $('externalSyncNoticeMessage'), externalSyncDismissBtn: $('externalSyncDismissBtn'), externalSyncCheckNowBtn: $('externalSyncCheckNowBtn'), statusText: $('statusText'),
  logToggleBtn: $('logToggleBtn'), logMenuText: $('logMenuText'), settingsModal: $('settingsModal'), closeSettingsBtn: $('closeSettingsBtn'), langSelect: $('langSelect'),
  updateAppModal: $('updateAppModal'), closeUpdateAppBtn: $('closeUpdateAppBtn'), updateInstalledVersionValue: $('updateInstalledVersionValue'), updateAvailableVersionValue: $('updateAvailableVersionValue'), updateCheckStatusText: $('updateCheckStatusText'), updateVerifyAgainBtn: $('updateVerifyAgainBtn'), updateApplyBtn: $('updateApplyBtn'), updateBackupsBox: $('updateBackupsBox'), updateChangelogBox: $('updateChangelogBox'), updateCloseBtn: $('updateCloseBtn'),
  openLastToggle: $('openLastToggle'), versionLimitSelect: $('versionLimitSelect'), codeEditor: $('codeEditor'), codeEditorFallback: $('codeEditorFallback'), charCount: $('charCount'), copyHtmlBtn: $('copyHtmlBtn'), editorPanelMenuBtn: $('editorPanelMenuBtn'),
  previewFrame: $('previewFrame'), previewStatus: $('previewStatus'), previewPanelMenuBtn: $('previewPanelMenuBtn'), previewFocusBtn: $('previewFocusBtn'), previewFocusExitBtn: $('previewFocusExitBtn'), splitter: $('splitter'), splitArea: $('splitArea'), editorPane: $('editorPane'), previewPane: $('previewPane'), dragOverlay: $('dragOverlay'),
  searchModal: $('searchModal'), closeSearchBtn: $('closeSearchBtn'), globalSearchInput: $('globalSearchInput'), globalSearchResults: $('globalSearchResults'),
  pageContextMenu: $('pageContextMenu'), moveProjectMenu: $('moveProjectMenu'), projectContextMenu: $('projectContextMenu'), editorPanelMenu: $('editorPanelMenu'), previewPanelMenu: $('previewPanelMenu'), createProjectModal: $('createProjectModal'), createProjectNameInput: $('createProjectNameInput'), closeCreateProjectBtn: $('closeCreateProjectBtn'), cancelCreateProjectBtn: $('cancelCreateProjectBtn'), confirmCreateProjectBtn: $('confirmCreateProjectBtn'),
  historyModal: $('historyModal'), closeHistoryBtn: $('closeHistoryBtn'), historyList: $('historyList'), logPanel: $('logPanel'), apiUsageSummaryBox: $('apiUsageSummaryBox'), logBox: $('logBox'), clearLogBtn: $('clearLogBtn'),
  confirmModal: $('confirmModal'), confirmBox: $('confirmBox'), confirmTitle: $('confirmTitle'), confirmMessage: $('confirmMessage'), confirmCancelBtn: $('confirmCancelBtn'), confirmOkBtn: $('confirmOkBtn'), deletePreviewWrap: $('deletePreviewWrap'), deletePreviewFrame: $('deletePreviewFrame'), confirmOpenPreviewBtn: $('confirmOpenPreviewBtn'),
  unsavedTransitionModal: $('unsavedTransitionModal'), unsavedTransitionSaveBtn: $('unsavedTransitionSaveBtn'), unsavedTransitionKeepDraftBtn: $('unsavedTransitionKeepDraftBtn'), unsavedTransitionDiscardBtn: $('unsavedTransitionDiscardBtn'), unsavedTransitionCancelBtn: $('unsavedTransitionCancelBtn'),
  draftRecoveryModal: $('draftRecoveryModal'), draftRecoveryTitle: $('draftRecoveryTitle'), draftRecoverySubtitle: $('draftRecoverySubtitle'), draftCurrentColumn: $('draftCurrentColumn'), draftLocalColumn: $('draftLocalColumn'), draftCodeDiffLegend: $('draftCodeDiffLegend'), draftCodeDiffMonaco: $('draftCodeDiffMonaco'), draftCodeDiffFallback: $('draftCodeDiffFallback'), draftFallbackCurrentPane: $('draftFallbackCurrentPane'), draftFallbackLocalPane: $('draftFallbackLocalPane'), closeDraftRecoveryBtn: $('closeDraftRecoveryBtn'), restoreDraftBtn: $('restoreDraftBtn'), keepCurrentVersionBtn: $('keepCurrentVersionBtn'), discardDraftBtn: $('discardDraftBtn'),
  reopenRecoveryBtn: $('reopenRecoveryBtn')
};
