const $ = <T extends HTMLElement = HTMLElement>(id: string): T => document.getElementById(id) as T;
const els = {
  sidebar: $('sidebar'), brandBtn: $<HTMLButtonElement>('brandBtn'), toggleSidebarBtn: $<HTMLButtonElement>('toggleSidebarBtn'), sidebarCloseIcon: $('sidebarCloseIcon'), sidebarOpenIcon: $('sidebarOpenIcon'), sidebarScroll: $('sidebarScroll'), sidebarProjectsSection: $('sidebarProjectsSection'), sidebarProjectsList: $('sidebarProjectsList'), newProjectBtn: $<HTMLButtonElement>('newProjectBtn'), sidebarPagesList: $('sidebarPagesList'), refreshSidebarBtn: $<HTMLButtonElement>('refreshSidebarBtn'), sidebarLoadMoreWrap: $('sidebarLoadMoreWrap'), sidebarLoadMoreBtn: $<HTMLButtonElement>('sidebarLoadMoreBtn'), searchPagesBtn: $<HTMLButtonElement>('searchPagesBtn'), sidebarSettingsBtn: $<HTMLButtonElement>('sidebarSettingsBtn'),
  pageHeader: $('pageHeader'), welcomeView: $('welcomeView'), welcomeNewPageBtn: $<HTMLButtonElement>('welcomeNewPageBtn'), welcomeSearchInput: $<HTMLInputElement>('welcomeSearchInput'), welcomeSearchResults: $('welcomeSearchResults'),
  saveBtn: $<HTMLButtonElement>('saveBtn'), updateAppBtn: $<HTMLButtonElement>('updateAppBtn'), refreshBtn: $<HTMLButtonElement>('refreshBtn'), openViewMenuBtn: $<HTMLButtonElement>('openViewMenuBtn'), newPageBtn: $<HTMLButtonElement>('newPageBtn'), historyBtn: $<HTMLButtonElement>('historyBtn'), deleteBtn: $<HTMLButtonElement>('deleteBtn'), moreBtn: $<HTMLButtonElement>('moreBtn'), moreMenu: $('moreMenu'),
  quickBothBtn: $<HTMLButtonElement>('quickBothBtn'), quickEditorBtn: $<HTMLButtonElement>('quickEditorBtn'), quickPreviewBtn: $<HTMLButtonElement>('quickPreviewBtn'),
  titleInput: $<HTMLInputElement>('titleInput'), descriptionInput: $<HTMLInputElement>('descriptionInput'), dirtyBadge: $('dirtyBadge'), externalSyncNotice: $('externalSyncNotice'), externalSyncNoticeTitle: $('externalSyncNoticeTitle'), externalSyncNoticeMessage: $('externalSyncNoticeMessage'), externalSyncDismissBtn: $<HTMLButtonElement>('externalSyncDismissBtn'), externalSyncCheckNowBtn: $<HTMLButtonElement>('externalSyncCheckNowBtn'), statusText: $('statusText'),
  logToggleBtn: $<HTMLButtonElement>('logToggleBtn'), logMenuText: $('logMenuText'), settingsModal: $('settingsModal'), closeSettingsBtn: $<HTMLButtonElement>('closeSettingsBtn'), langSelect: $<HTMLSelectElement>('langSelect'),
  updateAppModal: $('updateAppModal'), closeUpdateAppBtn: $<HTMLButtonElement>('closeUpdateAppBtn'), updateInstalledVersionValue: $('updateInstalledVersionValue'), updateAvailableVersionValue: $('updateAvailableVersionValue'), updateCheckStatusText: $('updateCheckStatusText'), updateVerifyAgainBtn: $<HTMLButtonElement>('updateVerifyAgainBtn'), updateApplyBtn: $<HTMLButtonElement>('updateApplyBtn'), updateBackupsBox: $('updateBackupsBox'), updateChangelogBox: $('updateChangelogBox'), updateCloseBtn: $<HTMLButtonElement>('updateCloseBtn'),
  openLastToggle: $<HTMLInputElement>('openLastToggle'), versionLimitSelect: $<HTMLSelectElement>('versionLimitSelect'), codeEditor: $('codeEditor'), codeEditorFallback: $<HTMLTextAreaElement>('codeEditorFallback'), charCount: $('charCount'), copyHtmlBtn: $<HTMLButtonElement>('copyHtmlBtn'), editorPanelMenuBtn: $<HTMLButtonElement>('editorPanelMenuBtn'),
  previewFrame: $<HTMLIFrameElement>('previewFrame'), previewStatus: $('previewStatus'), previewPanelMenuBtn: $<HTMLButtonElement>('previewPanelMenuBtn'), previewFocusBtn: $<HTMLButtonElement>('previewFocusBtn'), previewFocusExitBtn: $<HTMLButtonElement>('previewFocusExitBtn'), splitter: $('splitter'), splitArea: $('splitArea'), editorPane: $('editorPane'), previewPane: $('previewPane'), dragOverlay: $('dragOverlay'),
  searchModal: $('searchModal'), closeSearchBtn: $<HTMLButtonElement>('closeSearchBtn'), globalSearchInput: $<HTMLInputElement>('globalSearchInput'), globalSearchResults: $('globalSearchResults'),
  pageContextMenu: $('pageContextMenu'), moveProjectMenu: $('moveProjectMenu'), projectContextMenu: $('projectContextMenu'), editorPanelMenu: $('editorPanelMenu'), previewPanelMenu: $('previewPanelMenu'), createProjectModal: $('createProjectModal'), createProjectNameInput: $<HTMLInputElement>('createProjectNameInput'), closeCreateProjectBtn: $<HTMLButtonElement>('closeCreateProjectBtn'), cancelCreateProjectBtn: $<HTMLButtonElement>('cancelCreateProjectBtn'), confirmCreateProjectBtn: $<HTMLButtonElement>('confirmCreateProjectBtn'),
  historyModal: $('historyModal'), closeHistoryBtn: $<HTMLButtonElement>('closeHistoryBtn'), historyList: $('historyList'), logPanel: $('logPanel'), apiUsageSummaryBox: $('apiUsageSummaryBox'), logBox: $('logBox'), clearLogBtn: $<HTMLButtonElement>('clearLogBtn'),
  confirmModal: $('confirmModal'), confirmBox: $('confirmBox'), confirmTitle: $('confirmTitle'), confirmMessage: $('confirmMessage'), confirmCancelBtn: $<HTMLButtonElement>('confirmCancelBtn'), confirmOkBtn: $<HTMLButtonElement>('confirmOkBtn'), deletePreviewWrap: $('deletePreviewWrap'), deletePreviewFrame: $<HTMLIFrameElement>('deletePreviewFrame'), confirmOpenPreviewBtn: $<HTMLButtonElement>('confirmOpenPreviewBtn'),
  unsavedTransitionModal: $('unsavedTransitionModal'), unsavedTransitionSaveBtn: $<HTMLButtonElement>('unsavedTransitionSaveBtn'), unsavedTransitionKeepDraftBtn: $<HTMLButtonElement>('unsavedTransitionKeepDraftBtn'), unsavedTransitionDiscardBtn: $<HTMLButtonElement>('unsavedTransitionDiscardBtn'), unsavedTransitionCancelBtn: $<HTMLButtonElement>('unsavedTransitionCancelBtn'),
  draftRecoveryModal: $('draftRecoveryModal'), draftRecoveryTitle: $('draftRecoveryTitle'), draftRecoverySubtitle: $('draftRecoverySubtitle'), draftCurrentColumn: $('draftCurrentColumn'), draftLocalColumn: $('draftLocalColumn'), draftCodeDiffLegend: $('draftCodeDiffLegend'), draftCodeDiffMonaco: $('draftCodeDiffMonaco'), draftCodeDiffFallback: $('draftCodeDiffFallback'), draftFallbackCurrentPane: $('draftFallbackCurrentPane'), draftFallbackLocalPane: $('draftFallbackLocalPane'), closeDraftRecoveryBtn: $<HTMLButtonElement>('closeDraftRecoveryBtn'), restoreDraftBtn: $<HTMLButtonElement>('restoreDraftBtn'), keepCurrentVersionBtn: $<HTMLButtonElement>('keepCurrentVersionBtn'), discardDraftBtn: $<HTMLButtonElement>('discardDraftBtn'),
  reopenRecoveryBtn: $<HTMLButtonElement>('reopenRecoveryBtn'),
  conflictCompareModal: $('conflictCompareModal'), conflictCompareTitle: $('conflictCompareTitle'), conflictCompareSubtitle: $('conflictCompareSubtitle'), conflictLocalColumn: $('conflictLocalColumn'), conflictRemoteColumn: $('conflictRemoteColumn'), conflictCodeDiffLegend: $('conflictCodeDiffLegend'), conflictCodeDiffMonaco: $('conflictCodeDiffMonaco'), conflictCodeDiffFallback: $('conflictCodeDiffFallback'), conflictFallbackLeftPane: $('conflictFallbackLeftPane'), conflictFallbackRightPane: $('conflictFallbackRightPane'), conflictKeepLocalBtn: $<HTMLButtonElement>('conflictKeepLocalBtn'), conflictLoadRemoteBtn: $<HTMLButtonElement>('conflictLoadRemoteBtn'), conflictCompareOpenBtn: $<HTMLButtonElement>('conflictCompareOpenBtn')
};
