const I18N = {
  en: {
    save: 'Save', newPage: 'New Page', history: 'History', settings: 'Settings', deletePage: 'Delete', openLast: 'Open last page on startup',
    versionLimit: 'Local version limit', manualHistoryLimit: 'Manual history limit', unlimited: 'Unlimited', historyLocalNote: 'Version history is saved only in this browser.',
    editor: 'Editor', preview: 'Preview', openView: 'Open preview', title: 'Title', description: 'Description', view: 'Preview', unsaved: 'Unsaved', saved: 'Saved', saving: 'Saving...',
    noPage: 'No page selected', pageLoaded: 'Page loaded', pageCreated: 'New page draft', selectOrCreate: 'Select or create a page', restore: 'Restore', confirmRestore: 'Restore this version and save it to Fibery?', noHistory: 'No local history for this page.',
    searchPages: 'Search pages...', searchPagesShort: 'Search pages', recentPages: 'Recent', validationTitle: 'Page title is required.', readOnly: 'Read-only: admin permission not detected.',
    createPageTitle: 'Create new page draft?', createPageMessage: 'A blank page will be opened locally. It will only be created in Fibery when you press Save.', create: 'Create', cancel: 'Cancel',
    deleteTitle: 'Delete this page?', deleteMessage: 'This action cannot be undone. Confirm only if this is really the page you want to delete.', deleteConfirm: 'Delete', deleted: 'Page deleted',
    today: 'Today', yesterday: 'Yesterday', last7: 'Previous 7 days', last30: 'Previous 30 days', older: 'Older', allPages: 'All pages', noPages: 'No pages found', showLog: 'Show log', hideLog: 'Hide log',
    welcomeTitle: 'Welcome', welcomeSubtitle: 'What are we creating today?', welcomeSearch: 'Search pages...', loadMore: 'Load more', loading: 'Loading...', showBoth: 'Show both', onlyEditor: 'Only editor', onlyPreview: 'Only preview',
    copyHtml: 'Copy HTML', copyPreviewLink: 'Copy preview link', copiedCode: 'Code copied', copiedPreviewLink: 'Preview link copied', editorActions: 'Editor actions', previewActions: 'Preview actions', pasteReplace: 'Paste and replace', importHtml: 'Import HTML file', htmlImported: 'HTML imported', importHtmlError: 'Could not import HTML', selectAllCode: 'Select all code', codeSelected: 'Code selected', pastedReplaced: 'Code replaced', pasteReplacePrompt: 'Paste the code that will replace the current editor content:', refreshPreview: 'Refresh preview', previewFocus: 'Preview focus mode', exitPreviewFocus: 'Exit preview focus', showingPreview: 'Showing preview', closePreview: 'Close preview', copyFailed: 'Could not copy', updateApp: 'Update App', appPageMarker: 'Editor app page', projects: 'Projects', newProject: 'New project', untitledProject: 'Untitled project', deleteProject: 'Delete project', deleteProjectTitle: 'Delete this project?', deleteProjectMessage: 'This removes only the local project organization. It does not delete any Fibery page.', noProjects: 'No projects yet', addCurrentToProject: 'Add current page', addedToProject: 'Page added to project', currentPageRequired: 'Select or save a page first.', pageAlreadyInProject: 'This page is already in this project.', removedFromProject: 'Page removed from project', rename: 'Rename', copyPageLink: 'Copy page link', copiedPageLink: 'Page link copied', pin: 'Pin', unpin: 'Unpin', archive: 'Archive', unarchive: 'Unarchive', moveToProject: 'Move to project', openPreview: 'Open preview', removeFromProjectNamed: 'Remove from {project}', renameProject: 'Rename project', createProjectTitle: 'Create project', projectNameLabel: 'Project name', projectLocalNote: 'Projects are saved only in this browser.', createProjectButton: 'Create project', projectCreated: 'Project created', pageMovedToProject: 'Page moved to project', pageRenamed: 'Page renamed', projectRenamed: 'Project renamed', pinned: 'Pinned', unpinned: 'Unpinned', archived: 'Archived', unarchived: 'Unarchived', renameEmptyIgnored: 'Name cannot be empty.'
  },
  'pt-BR': {
    save: 'Salvar', newPage: 'Nova página', history: 'Histórico', settings: 'Configurações', deletePage: 'Apagar', openLast: 'Abrir última página ao iniciar',
    versionLimit: 'Limite de versões locais', manualHistoryLimit: 'Limite do histórico manual', unlimited: 'Sem limite', historyLocalNote: 'O histórico fica salvo apenas neste navegador.',
    editor: 'Editor', preview: 'Prévia', openView: 'Abrir prévia', title: 'Título', description: 'Descrição', view: 'Prévia', unsaved: 'Não salvo', saved: 'Salvo', saving: 'Salvando...',
    noPage: 'Nenhuma página selecionada', pageLoaded: 'Página carregada', pageCreated: 'Rascunho criado', selectOrCreate: 'Selecione ou crie uma página', restore: 'Restaurar', confirmRestore: 'Restaurar esta versão e salvar no Fibery?', noHistory: 'Sem histórico local para esta página.',
    searchPages: 'Buscar páginas...', searchPagesShort: 'Buscar páginas', recentPages: 'Recentes', validationTitle: 'O título da página é obrigatório.', readOnly: 'Somente leitura: permissão de admin não detectada.',
    createPageTitle: 'Criar nova página?', createPageMessage: 'Uma página vazia será aberta localmente. Ela só será criada no Fibery quando você clicar em Salvar.', create: 'Criar', cancel: 'Cancelar',
    deleteTitle: 'Excluir esta página?', deleteMessage: 'Essa ação não pode ser desfeita. Confirme somente se esta for realmente a página que você quer excluir.', deleteConfirm: 'Apagar', deleted: 'Página excluída',
    today: 'Hoje', yesterday: 'Ontem', last7: '7 dias anteriores', last30: '30 dias anteriores', older: 'Mais antigas', allPages: 'Todas as páginas', noPages: 'Nenhuma página encontrada', showLog: 'Mostrar log', hideLog: 'Ocultar log',
    welcomeTitle: 'Bem-vindo', welcomeSubtitle: 'O que vamos criar hoje?', welcomeSearch: 'Buscar páginas...', loadMore: 'Carregar mais', loading: 'Carregando...', showBoth: 'Mostrar editor e prévia', onlyEditor: 'Mostrar só editor', onlyPreview: 'Mostrar só prévia',
    copyHtml: 'Copiar HTML', copyPreviewLink: 'Copiar link da prévia', copiedCode: 'Código copiado', copiedPreviewLink: 'Link da prévia copiado', editorActions: 'Ações do editor', previewActions: 'Ações da prévia', pasteReplace: 'Colar e substituir', importHtml: 'Importar de HTML', htmlImported: 'HTML importado', importHtmlError: 'Não foi possível importar o HTML', selectAllCode: 'Selecionar todo o código', codeSelected: 'Código selecionado', pastedReplaced: 'Código substituído', pasteReplacePrompt: 'Cole o código que vai substituir o conteúdo atual do editor:', refreshPreview: 'Atualizar prévia', previewFocus: 'Modo foco da prévia', exitPreviewFocus: 'Sair do modo foco', showingPreview: 'Mostrando prévia', closePreview: 'Fechar prévia', copyFailed: 'Não foi possível copiar', updateApp: 'Atualizar App', appPageMarker: 'Página do app editor', projects: 'Projetos', newProject: 'Novo projeto', untitledProject: 'Projeto sem nome', deleteProject: 'Apagar projeto', deleteProjectTitle: 'Apagar este projeto?', deleteProjectMessage: 'Isso remove apenas a organização local do projeto. Não apaga nenhuma página do Fibery.', noProjects: 'Nenhum projeto ainda', addCurrentToProject: 'Adicionar página atual', addedToProject: 'Página adicionada ao projeto', currentPageRequired: 'Selecione ou salve uma página primeiro.', pageAlreadyInProject: 'Esta página já está neste projeto.', removedFromProject: 'Página removida do projeto', rename: 'Renomear', copyPageLink: 'Copiar link da página', copiedPageLink: 'Link da página copiado', pin: 'Fixar', unpin: 'Desafixar', archive: 'Arquivar', unarchive: 'Desarquivar', moveToProject: 'Mover para projeto', openPreview: 'Abrir prévia', removeFromProjectNamed: 'Remover de {project}', renameProject: 'Renomear projeto', createProjectTitle: 'Criar projeto', projectNameLabel: 'Nome do projeto', projectLocalNote: 'Projetos ficam salvos apenas neste navegador.', createProjectButton: 'Criar projeto', projectCreated: 'Projeto criado', pageMovedToProject: 'Página movida para projeto', pageRenamed: 'Página renomeada', projectRenamed: 'Projeto renomeado', pinned: 'Página fixada', unpinned: 'Página desafixada', archived: 'Página arquivada', unarchived: 'Página desarquivada', renameEmptyIgnored: 'O nome não pode ficar vazio.'
  }
};
