import type { AppState } from './app';

declare global {
  type AppState = import('./app').AppState;
  type ApiUsageCall = import('./app').ApiUsageCall;
  type PanelMode = import('./app').PanelMode;
  type ApiUsageEntry = import('./app').ApiUsageEntry;
  type ApiUsageKind = import('./app').ApiUsageKind;
  type ApiUsageMeta = import('./app').ApiUsageMeta;
  type ApiUsageOperation = import('./app').ApiUsageOperation;
  type ApiUsageTask<TResult = unknown> = import('./app').ApiUsageTask<TResult>;
  type ConfirmActionOptions = import('./domain').ConfirmActionOptions;
  type ContentSignature = import('./domain').ContentSignature;
  type ConflictCandidate = import('./domain').ConflictCandidate;
  type ConflictResolution = import('./domain').ConflictResolution;
  type CreateUpdateBackupOptions = import('./storage').CreateUpdateBackupOptions;
  type DraftRecord = import('./storage').DraftRecord;
  type FetchRemoteTextOptions = import('./domain').FetchRemoteTextOptions;
  type FiberyCheckAdminOptions = import('./domain').FiberyCheckAdminOptions;
  type FiberyApiCallOptions = import('./domain').FiberyApiCallOptions;
  type FiberyDeletePageOptions = import('./domain').FiberyDeletePageOptions;
  type FiberyLoadPageOptions = import('./domain').FiberyLoadPageOptions;
  type FiberyLoadPagesOptions = import('./domain').FiberyLoadPagesOptions;
  type FiberyLoadPagesResult = import('./domain').FiberyLoadPagesResult;
  type FiberySaveResult = import('./domain').FiberySaveResult;
  type FiberySavePageOptions = import('./domain').FiberySavePageOptions;
  type FiberyPage = import('./domain').FiberyPage;
  type LocalEmergencyDraft = import('./storage').LocalEmergencyDraft;
  type LocalPreviewDocumentOptions = import('./domain').LocalPreviewDocumentOptions;
  type LocalPreviewMessagePayload = import('./domain').LocalPreviewMessagePayload;
  type LocalPreviewMessageType = import('./domain').LocalPreviewMessageType;
  type LocalPreviewStatusOptions = import('./domain').LocalPreviewStatusOptions;
  type PageId = import('./domain').PageId;
  type PageSnapshot = import('./domain').PageSnapshot;
  type PausePreviewOptions = import('./domain').PausePreviewOptions;
  type PreviewMode = import('./domain').PreviewMode;
  type RemoteStatus = import('./domain').RemoteStatus;
  type RealPreviewRenderOptions = import('./domain').RealPreviewRenderOptions;
  type ResumePreviewOptions = import('./domain').ResumePreviewOptions;
  type RollbackValidationReason = import('./domain').RollbackValidationReason;
  type RollbackValidationResult = import('./domain').RollbackValidationResult;
  type QueuePreviewSyncOptions = import('./domain').QueuePreviewSyncOptions;
  type SavePagePayload = import('./domain').SavePagePayload;
  type SaveBlockedReason = import('./domain').SaveBlockedReason;
  type SyncPreviewModeOptions = import('./domain').SyncPreviewModeOptions;
  type SyncPreviewVisibilityOptions = import('./domain').SyncPreviewVisibilityOptions;
  type SyncCurrentSnapshotOptions = import('./domain').SyncCurrentSnapshotOptions;
  type UnsavedChangeCheckOptions = import('./domain').UnsavedChangeCheckOptions;
  type UnsavedTransitionChoice = import('./domain').UnsavedTransitionChoice;
  type HistoryRecord = import('./storage').HistoryRecord;
  type SemverSimple = import('./domain').SemverSimple;
  type LocalStorageKeys = import('./storage').LocalStorageKeys;
  type RemoteUpdateValidationResult = import('./domain').RemoteUpdateValidationResult;
  type UpdateBackupListRecord = import('./storage').UpdateBackupListRecord;
  type UpdateBackupRecord = import('./storage').UpdateBackupRecord;
  type UpdateChangelogVersionHeading = import('./domain').UpdateChangelogVersionHeading;
  type UpdateCheckStatus = import('./domain').UpdateCheckStatus;
  type UpdateRemoteConfig = import('./domain').UpdateRemoteConfig;
  type UpdateValidationReason = import('./domain').UpdateValidationReason;
  type UpdateVersionComparisonState = import('./domain').UpdateVersionComparisonState;
  type ManualHistoryKind = import('./storage').ManualHistoryKind;
  type PageContentCacheRecord = import('./storage').PageContentCacheRecord;
  type PageMetaRecord = import('./storage').PageMetaRecord;
  type ProjectItemRecord = import('./storage').ProjectItemRecord;
  type ProjectRecord = import('./storage').ProjectRecord;
  type RequiredResourceStatus = import('./resources').RequiredResourceStatus;
  type ResourceCacheStatus = import('./resources').ResourceCacheStatus;
  type ResourceEncoding = import('./resources').ResourceEncoding;
  type ResourceKind = import('./resources').ResourceKind;
  type ResourceManifest = import('./resources').ResourceManifest;
  type ResourceManifestEntry = import('./resources').ResourceManifestEntry;
  type ResourceRecord = import('./resources').ResourceRecord;
  type ResourceValidationResult = import('./resources').ResourceValidationResult;

  interface MonacoEditorModel {
    dispose(): void;
    getValue(): string;
    setValue(value: string): void;
    getLineCount(): number;
    getLineMaxColumn(line: number): number;
  }
  interface MonacoLineChange {
    originalStartLineNumber: number;
    originalEndLineNumber: number;
    modifiedStartLineNumber: number;
    modifiedEndLineNumber: number;
  }
  interface MonacoDiffEditorInstance {
    dispose(): void;
    setModel(model: { original: MonacoEditorModel; modified: MonacoEditorModel }): void;
    onDidUpdateDiff(callback: () => void): void;
    getLineChanges(): MonacoLineChange[] | null;
    layout(): void;
  }
  interface MonacoSingleEditorInstance {
    getModel(): MonacoEditorModel | null;
    getValue(): string;
    updateOptions(options: Record<string, unknown>): void;
    onDidChangeModelContent(callback: () => void): void;
    focus(): void;
    setSelection(range: unknown): void;
  }
  interface MonacoEditorNamespace {
    createModel(value: string, language: string): MonacoEditorModel;
    createDiffEditor(element: HTMLElement, options: Record<string, unknown>): MonacoDiffEditorInstance;
    create(element: HTMLElement, options: Record<string, unknown>): MonacoSingleEditorInstance;
  }
  interface MonacoGlobal {
    editor: MonacoEditorNamespace;
    Range: new (startLineNumber: number, startColumn: number, endLineNumber: number, endColumn: number) => unknown;
  }
  interface AmdRequire {
    (modules: string[], onLoad: () => void, onError?: () => void): void;
    config(options: { paths: Record<string, string> }): void;
  }
  interface Window { require?: AmdRequire; FIBERY_HTML_EDITOR_VERSION: string; }

  const monaco: MonacoGlobal | undefined;

  function closeCreateProjectModal(): void;
  function confirmAction(options?: ConfirmActionOptions): Promise<boolean>;
  function closeConfirm(result: unknown): void;
  function currentBaselineSnapshot(): PageSnapshot;
  function currentSnapshotFromState(): PageSnapshot;
  function clearEmergencyDraftForPage(pageId: PageId | ''): void;
  function clearSearchCaches(): void;
  function clearPreviewDebounce(): void;
  function deleteDraftByKey(key: string): Promise<void>;
  function deletePageContentCacheSafe(pageId: PageId | '', options?: { source?: string }): Promise<boolean>;
  function deletePageMeta(id: PageId | ''): Promise<void>;
  function draftKeyForPage(pageId?: string): string;
  function escapeHtml(v: unknown): string;
  function escapeHtmlAttr(v: unknown): string;
  function flushDraftAutosaveNow(): Promise<void>;
  function fetchRemoteText(url: string, options?: FetchRemoteTextOptions): Promise<string>;
  function getCodeValue(): string;
  function getHistory(pageId: PageId, kind?: 'all' | 'manual' | 'autosave'): Promise<HistoryRecord[]>;
  function getInstalledAppVersionFromCurrentState(): string;
  function getRollbackDisabledReasonText(): string;
  function getUpdateBackupRecordByKey(key?: string): Promise<UpdateBackupListRecord | null>;
  function getUpdateBackupTargetPageId(): string;
  function getMetaMap(): Record<string, PageMetaRecord>;
  function isSaveBlockedByRemoteVerification(): boolean;
  function isCurrentAppPageForUpdate(): boolean;
  function isPreviewPanelVisible(): boolean;
  function loadPageWithCacheAwareFlow(pageId: string, promptToken: number): Promise<void>;
  function loadSearchResults(options?: { localOnly?: boolean }): Promise<void>;
  function loadWelcomeSearchResults(options?: { localOnly?: boolean }): Promise<void>;
  function log(message: string): void;
  function logPreviewModeChange(nextMode: PreviewMode | string, previousMode: PreviewMode | string): void;
  function markDirty(value?: boolean): void;
  function markCurrentPageRemoteVerified(options?: { remoteStatus?: RemoteStatus; openedFromCache?: boolean; signature?: string }): void;
  function apiUsageNow(): number;
  function apiUsageErrorText(error: unknown): string;
  function apiUsageCallKey(entry?: ApiUsageMeta): string;
  function isApiUsageLogVisible(): boolean;
  function renderApiUsageSummary(): void;
  function recordApiUsage(entry?: ApiUsageEntry): ApiUsageCall;
  function clearApiUsageStats(): void;
  function withApiUsage<TResult = unknown>(meta: ApiUsageMeta, task: ApiUsageTask<TResult>): Promise<TResult>;
  function htmlUsesTailwindStylesheet(html?: string): boolean;
  function handleLocalPreviewMessage(event: MessageEvent<LocalPreviewMessagePayload>): void;
  function automaticFiberyCooldownRemaining(now?: number): number;
  function localPreviewBaseHref(): string;
  function localPreviewRequestId(): string;
  function localPreviewRenderSignature(html: string, baseHref: string, usesTailwind: boolean): ContentSignature;
  function localPreviewStatusLabel(options?: LocalPreviewStatusOptions): string;
  function localPreviewProbeScript(options?: LocalPreviewDocumentOptions): string;
  function loadUpdateBackupList(): Promise<void>;
  function previewHeaderStatusLabel(): string;
  function pausePreviewIfHidden(options?: PausePreviewOptions): boolean;
  function queuePreviewSync(options?: QueuePreviewSyncOptions): void;
  function rebuildProjectMaps(): void;
  function parseSemverSimple(version?: string): SemverSimple | null;
  function compareSemverSimple(a: SemverSimple, b: SemverSimple): number;
  function parseAppVersionFromHtmlSource(html?: string): string;
  function extractRemoteVersionFromHtml(html?: string): string;
  function extractVersionFromUpdateBackupHtml(record?: UpdateBackupListRecord): string;
  function formatUpdateBackupVersionLabel(record?: UpdateBackupListRecord): string;
  function formatUpdateBackupCreatedAt(createdAt: unknown): string;
  function isSafeUpdateBackupRecord(record?: UpdateBackupListRecord): boolean;
  function createUpdateBackupRecord(options: CreateUpdateBackupOptions): Promise<UpdateBackupRecord>;
  function refreshPreview(): void;
  function refreshSidebarFromLocalCache(options?: unknown): void;
  function renderLocalPreview(): void;
  function renderRealPreview(options?: RealPreviewRenderOptions): void;
  function renderCurrent(): void;
  function renderSidebarProjects(): void;
  function setCodeValue(value: string): void;
  function setCodeReadOnly(readOnly: boolean): void;
  function setupCodeEditor(): Promise<boolean>;
  function updateSidebarActiveState(): void;
  function showWorkspace(): void;
  function setPanelMode(mode: string, persist?: boolean): void;
  function updateCharCount(): void;
  function enterPreviewFocus(): void;
  function exitPreviewFocus(): void;
  function setupResize(): void;
  function setSplit(pct: number): void;
  function openHistoryModal(): Promise<void>;
  function closeHistoryModal(): void;
  function historyRowHtml(row: HistoryRecord): string;
  function renderHistory(): Promise<void>;
  function restoreVersion(key: string): Promise<void>;
  function openDraftRecoveryModal(options?: DraftRecoveryModalOptions): void;
  function renderUpdateChangelog(container: HTMLElement, rawChangelog: string, comparison: UpdateVersionComparisonState): void;
  function renderUpdateAppPanel(): void;
  function renderUpdateBackupList(): void;
  function openUpdateAppModal(): void;
  function closeUpdateAppModal(): void;
  function revokeLocalPreviewObjectUrl(): void;
  function hasRealUnsavedChangesForCurrentPage(options?: UnsavedChangeCheckOptions): boolean;
  function resumePreviewIfVisible(options?: ResumePreviewOptions): boolean;
  function resetCachedPageOpenState(pageId?: string): void;
  function resetExternalSyncStateForCurrentPage(pageId?: string): void;
  function saveHistory(action?: string): Promise<void>;
  function savePageContentCacheSafe(
    snapshot?: Partial<PageSnapshot & FiberyPage & PageContentCacheRecord>,
    options?: { pageId?: PageId; cachedAt?: number; verifiedAt?: number; source?: string; signature?: ContentSignature }
  ): Promise<PageContentCacheRecord | null>;
  function savePageMeta(id: PageId | '', data?: Partial<PageMetaRecord>): Promise<PageMetaRecord | null>;
  function saveBlockedReasonForCurrentPage(): SaveBlockedReason;
  function saveCurrentDraftNow(options?: { force?: boolean }): Promise<DraftRecord | null>;
  function scheduleLocalPreviewRefresh(): void;
  function setCurrentBaseline(): void;
  function showBlankPage(): void;
  function sameSnapshot(a?: Partial<PageSnapshot> | null, b?: Partial<PageSnapshot> | null): boolean;
  function shouldUseLocalPreview(): boolean;
  function syncDirtyWithBaseline(): void;
  function snapshotSignature(snapshot?: Partial<PageSnapshot> | null): ContentSignature;
  function shouldForceLocalPreviewForCachedOpen(): boolean;
  function canRunAutomaticFiberyCall(source?: string): boolean;
  function canShowApplyUpdateButton(): boolean;
  function canApplyUpdateNow(): boolean;
  function clearExternalSyncCandidateForCurrentPage(options?: { clearDismissed?: boolean; clearNotified?: boolean }): void;
  function automaticFiberySkipReason(source?: string): string;
  function logAutomaticFiberySkip(source?: string, reason?: string): void;
  function recordPreviewUsage(options?: { operation?: ApiUsageOperation; source?: string; pageId?: string; automatic?: boolean }): void;
  function setStatus(text: string): void;
  function syncBeforeUnloadWarningState(): void;
  function syncCachedOpenCheckNowButtonLabel(): void;
  function syncCurrentSnapshotBaselineAndDirty(options?: SyncCurrentSnapshotOptions): void;
  function syncExternalSyncPollingState(options?: { forceReschedule?: boolean }): void;
  function syncSaveAvailabilityState(options?: { announce?: boolean }): boolean;
  function syncPreviewMode(options?: SyncPreviewModeOptions): void;
  function syncPreviewVisibilityState(options?: SyncPreviewVisibilityOptions): boolean;
  function cachePagesForSidebar(rows: FiberyPage[]): void;
  function savePage(action?: string): Promise<boolean>;
  function applyRemoteUpdate(): Promise<void>;
  function restoreUpdateBackupByKey(key?: string): Promise<void>;
  function updateStatusMessage(): string;
  function validateUpdateBackupForRollback(record?: UpdateBackupListRecord): RollbackValidationResult;
  function validateRemoteUpdateHtml(remoteHtml?: string): RemoteUpdateValidationResult;
  function updateRollbackValidationReasonText(reason?: RollbackValidationReason | string): string;
  function updateValidationReasonText(reason?: UpdateValidationReason | string): string;
  function checkRemoteUpdateInfo(): Promise<void>;
  function t(key: string): string;
  function txPut<TValue>(storeName: 'versions' | 'pageMeta' | 'projects' | 'projectItems' | 'drafts' | 'pageContentCache' | 'appResources', value: TValue): Promise<void>;
  function updateCurrentFromInputs(): void;
  function viewUrl(id: string): string;
  function updatePreviewHeaderStatus(): void;

  function showToastNear(target: Element, message: string): void;
  function copyText(text: string, target: Element, okMessage: string): Promise<void>;
  function preferredLang(): string;

  // Migrated functions
  function normalizePageRows(rows: FiberyPage[]): FiberyPage[];
  function pageListSignature(pages: FiberyPage[]): string;
  function savedLocalPages(): FiberyPage[];
  function knownLocalPages(): FiberyPage[];
  function sidebarPagesFromCache(): FiberyPage[];
  function shouldUseRecentSidebarRemoteLoad(options?: { force?: boolean }): boolean;
  function loadSidebarPages(options?: { force?: boolean; append?: boolean; reset?: boolean; automatic?: boolean; source?: string; remote?: boolean } | boolean): Promise<void>;
  function codeIconSvg(className?: string): string;
  function appPageBadge(pageId: string): string;
  function projectPageIds(): Set<string>;
  function moreIconSvg(className?: string): string;
  function archivedBadge(pageId: string): string;
  function pageMenuButton(pageId: string, title: string, projectId?: string): string;
  function projectMenuButton(projectId: string, projectName: string): string;
  function pageItemHtml(page: FiberyPage, compact?: boolean): string;
  function renderSidebarPages(): void;
  function updateSidebarLoadMore(): void;
  function startSidebarAutoRefresh(): void;
  function stopSidebarAutoRefresh(): void;
  function setSidebarOpen(open: boolean, persist?: boolean): void;
  function searchCacheEntry(searchState: SearchState, query: string): { at: number; pages: FiberyPage[] } | null;
  function setSearchCacheEntry(searchState: SearchState, query: string, pages: FiberyPage[]): void;
  function localSearchRows(query?: string, limit?: number): FiberyPage[];
  function openSearchModal(): void;
  function closeSearchModal(): void;
  function searchRowHtml(page: FiberyPage, compact?: boolean): string;
  function renderSearchResults(rows: FiberyPage[]): void;
  function openWelcomeSearch(): void;
  function closeWelcomeSearch(): void;
  function renderWelcomeSearchResults(rows: FiberyPage[]): void;
  function getPageSnapshot(pageId: string): { id: string; title: string; description: string };
  function projectPageItemHtml(item: ProjectItemRecord): string;
  function openCreateProjectModal(targetPageId?: string): void;
  function positionFloatingMenu(menu: HTMLElement, x: number, y: number): void;
  function closeContextMenus(): void;
  function shouldToggleFloatingMenu(menu: HTMLElement | null, trigger: Element | EventTarget | null): boolean;
  function openEditorPanelMenu(event: MouseEvent): void;
  function selectAllCode(target: Element): void;
  function pasteReplaceCode(target: Element): Promise<void>;
  function importHtmlFile(target: Element | null): void;
  function openPreviewPanelMenu(event: MouseEvent): void;
  function openPageContextMenu(event: MouseEvent, pageId: string, pageTitle?: string, projectId?: string): void;
  function openMoveProjectMenu(anchor: Element): void;
  function openProjectContextMenu(event: MouseEvent, projectId: string, projectTitle?: string): void;
  function startInlineRenameTitle(pageId: string): void;
  function startInlineRenameProject(projectId: string): void;
  function openSettings(): void;
  function closeSettings(): void;
  function toggleLog(): void;
  function setAdminMode(isAdmin: boolean): void;
  function applyI18n(): void;
  function bindEvents(): void;
  function init(): Promise<void>;
  function putResourceRecord(record: ResourceRecord): Promise<void>;
  function getResourceRecord(key: string): Promise<ResourceRecord | null>;
  function getAllResourceRecords(): Promise<ResourceRecord[]>;
  function deleteResourceRecord(key: string): Promise<void>;
  function getResourceContent(key: string): Promise<string | null>;
  function isResourceRecordCompatible(record: ResourceRecord | null, entry: ResourceManifestEntry): boolean;
  function normalizeResourceRecord(entry: ResourceManifestEntry, partial?: Partial<ResourceRecord>): ResourceRecord;
  function validateResourceEntryShape(entry: unknown): entry is ResourceManifestEntry;
  function sha256Hex(text: string): Promise<string>;
  function validateResourceContentHash(content: string, entry: ResourceManifestEntry): Promise<ResourceValidationResult>;
  function fetchResourceContent(entry: ResourceManifestEntry): Promise<string>;
  function downloadResourceEntry(entry: ResourceManifestEntry): Promise<ResourceRecord>;
  function getRequiredResourceStatuses(manifest: ResourceManifest): Promise<RequiredResourceStatus[]>;
  function downloadRequiredResources(manifest: ResourceManifest): Promise<RequiredResourceStatus[]>;
  function ensureRequiredResources(): Promise<void>;
  function retryRequiredResourcesDownload(): Promise<void>;
  function checkRequiredResources(): Promise<void>;
  function showResourceBootOverlay(): void;
  function hideResourceBootOverlay(): void;
  function renderResourceBootOverlay(): void;
  function initResourceBootEvents(): void;
  function parseI18nResource(content: string): Record<string, string> | null;
  function mergeI18nTranslations(lang: string, bundle: Record<string, string>): void;
  function loadCachedI18nResources(): Promise<boolean>;
  function applyI18nResourceBundle(): Promise<boolean>;
  function ensureI18nResourcesLoaded(): Promise<void>;

  type SearchState = import('./app').SearchState;

  var API: {
    checkIsAdmin(options?: FiberyCheckAdminOptions): Promise<boolean>;
    loadPages(options?: FiberyLoadPagesOptions): Promise<FiberyLoadPagesResult>;
    loadPage(id: string, options?: FiberyLoadPageOptions): Promise<FiberyPage | null>;
    savePage(page: SavePagePayload, options?: FiberySavePageOptions): Promise<FiberySaveResult>;
    deletePage(id: string, options?: FiberyDeletePageOptions): Promise<{ success: boolean }>;
  };
}

export {};
